# .pre-commit-config.yaml
repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.12.10

# Run pytest on every commit
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: python
        additional_dependencies: [pytest, ursina]
        stages: [pre-commit]
        pass_filenames: false
        always_run: true
        verbose: true